// Verbatim quotations of the repository LICENSE (whitespace and Markdown
// emphasis normalised). Never translate or paraphrase these: `npm run check`
// (scripts/check-license-quotes.mjs) fails when one is not in ../LICENSE.

export type QuoteId =
  | "use1"
  | "use2"
  | "use3"
  | "use4"
  | "usesAreCommercial"
  | "commercialUse"
  | "personalTradingGrant"
  | "personalTradingDef"
  | "personalTradingA"
  | "personalTradingB"
  | "noncommercialPurposes"
  | "personalUses"
  | "noncommercialOrgs"
  | "supplementalControl";

export const LICENSE_URL = "https://github.com/pineforge-4pass/pineforge-codegen-oss/blob/main/LICENSE";

/** Which LICENSE section each quotation comes from. */
export const LICENSE_QUOTE_SECTION: Record<QuoteId, string> = {
  use1: "Additional Permission — Personal Trading",
  use2: "Additional Permission — Personal Trading",
  use3: "Additional Permission — Personal Trading",
  use4: "Additional Permission — Personal Trading",
  usesAreCommercial: "Additional Permission — Personal Trading",
  commercialUse: "Commercial Use",
  personalTradingGrant: "Additional Permission — Personal Trading",
  personalTradingDef: "Additional Permission — Personal Trading",
  personalTradingA: "Additional Permission — Personal Trading",
  personalTradingB: "Additional Permission — Personal Trading",
  noncommercialPurposes: "PolyForm Noncommercial License 1.0.0 — Noncommercial Purposes",
  personalUses: "PolyForm Noncommercial License 1.0.0 — Personal Uses",
  noncommercialOrgs: "PolyForm Noncommercial License 1.0.0 — Noncommercial Organizations",
  supplementalControl: "Preamble",
};

export const LICENSE_QUOTES: Record<QuoteId, string> = {
  use1: "(1) managing, advising on, or trading capital belonging to any other person or entity, whether or not for a fee;",
  use2: "(2) use by, for, or on behalf of any company, fund, partnership, or other organization, including use by an individual in the course of work for such an organization;",
  use3: "(3) embedding the software, or output generated by it, into any product or service made available to others; or",
  use4: "(4) operating any hosted, software-as-a-service, or otherwise public-facing service that uses the software.",
  usesAreCommercial: "The use described in (1)–(4) is Commercial Use.",
  commercialUse: "Any use that is not a permitted purpose under the base license and is not covered by the Additional Permission above — including the uses listed in (1)–(4) of that section — requires a separate commercial license from the licensor.",
  personalTradingGrant: "Notwithstanding the limitation to noncommercial purposes in the base license, the licensor grants you, free of charge, an additional license to use the software for Personal Trading, and Personal Trading is hereby a permitted purpose under the base license — including its Copyright License, Distribution License, Changes and New Works License, and Patent License.",
  personalTradingDef: "Personal Trading means use of the software by a natural person to research, develop, backtest, and execute trades in financial instruments, where:",
  personalTradingA: "(a) the trades are placed for that same natural person's own account; and",
  personalTradingB: "(b) the trades are funded solely by that person's own capital.",
  noncommercialPurposes: "Any noncommercial purpose is a permitted purpose.",
  personalUses: "Personal use for research, experiment, and testing for the benefit of public knowledge, personal study, private entertainment, hobby projects, amateur pursuits, or religious observance, without any anticipated commercial application, is use for a permitted purpose.",
  noncommercialOrgs: "Use by any charitable organization, educational institution, public research organization, public safety or health organization, environmental protection organization, or government institution is use for a permitted purpose regardless of the source of funding or obligations resulting from the funding.",
  supplementalControl: "In case of any conflict, the supplemental sections (\"Additional Permission\" and \"Commercial Use\") control over the base license.",
};
